image: golang:1.25

stages:
  - test
  - build

variables:
  GOPATH: $CI_PROJECT_DIR/.go
  GOCACHE: $CI_PROJECT_DIR/.go/cache

cache:
  paths:
    - .go/

default:
  tags:
    - localdocker
  before_script:
    - go mod tidy

test:
  stage: test
  script:
    - go test ./... -v -timeout 120s

build:
  stage: build
  script:
    - go build -o terraform-provider-hestiacp .
  artifacts:
    paths:
      - terraform-provider-hestiacp
    expire_in: 1 week
